### ISSUE TITLE
Fatal error if image file is missing or corrupt on server

### ISSUE THREAD

**Issue by joshuafredrickson** [Booreiland/responsive-pics#33]
**Describe the bug**
If an image exists in the database (e.g., it has an attachment ID), but for some reason the file itself is missing from the server or corrupt, a fatal error is triggered. In some flavors of Sage, this produces a white screen.

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function RP_Process::process_resize_request(), 7 passed in /path/to/web/wp/wp-includes/class-wp-hook.php on line 307 and exactly 8 expected in /path/to/web/app/plugins/responsive-pics/src/class-process.php:458
Stack trace:
#0 /path/to/web/wp/wp-includes/class-wp-hook.php(307): RP_Process::process_resize_request(55199, 90, 510, 680, false, 1, '/srv/www/site.c...')
#1 /path/to/web/wp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#2 /path/to/web/wp/wp-includes/plugin.php(524): WP_Hook->do_action(Array)
#3 /path/to/web/app/plugins/responsive-pics/lib/action-scheduler/classes/actions/ActionScheduler_Action.php(43): do_action_ref_array('process_resize_...', Array)
#4 /path/to/web/app/plugins/responsive-pics/lib/acti in /path/to/web/app/plugins/responsive-pics/src/class-process.php on line 458
```

**Expected behavior**
Responsive Pics should silently fail and not trigger a fatal error.

**Software (please complete the following information):**
 - PHP Version: Experienced in both 7.4 and 8.0
 - ResponsivePicture version: 1.6.2
 - Wordpress version: 6.0.x, 6.1

**Additional context**
I've seen this happen with images that have disappeared from the server (e.g., no longer in the filesystem) as well as with corrupted images.

**Comment by Twansparant** [comment]
Thanks for this, I'll have a look. Does this happen when the original file is missing/corrupt? And only when they're still in the action scheduler queue? Otherwise you should just get a broken image in your frontend...
The white screen in sage might be caused by the buggy Acorn error handling (if you're using Acorn that is).

**Comment by Twansparant** [comment]
```
Uncaught ArgumentCountError: Too few arguments to function RP_Process::process_resize_request(), 7 passed in /path/to/web/wp/wp-includes/class-wp-hook.php on line 307 and exactly 8 expected in /path/to/web/app/plugins/responsive-pics/src/class-process.php:458
```
This error indicates that the action being processed in the queue only passed 7 parameters, while it should it be 8 since version `1.6.2`. Could you try removing any pending actions left in the queue and refresh the page?

**Comment by joshuafredrickson** [comment]
Interesting. Sounds like you're saying that after updating to 1.6.2, any existing actions from prior versions queued in action-scheduler are invalid and could error out. Would that also then trigger the PHP fatal error on the frontend during page load?

I've seen it on two separate sites now. Both had corrupt images/missing files that needed to be sorted. Both were also in a staging environment, so it's entirely possible that cron jobs weren't running. 

If that's the case, then clearing the action scheduler queue is an easy fix.

**Comment by Twansparant** [comment]
> Would that also then trigger the PHP fatal error on the frontend during page load?

It must be, because that's the only function that will return a fatal error. I tested and removed some files that were still in the database, but that should still return a valid image html but with a 404 on the actual image url.

**Comment by joshuafredrickson** [comment]
I downgraded to 1.5.2, added some batches, updated to 1.6.2 and removed the source image. 

I received that exact error when I manually triggered action-scheduler, so I think you're exactly right in that being the issue. I'll go ahead and close this for now as the fix appears to be clearing pending actions from `wp_actionscheduler_actions`.

Thanks for the assist!
